{{- if .Values.argocdIngress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: argocd-ingress
  {{- with .Values.argocdIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.argocdIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.argocdIngress.className }}
  {{- end }}
  rules:
  - http:
      paths:
        - path: {{ .Values.argocdIngress.path }}
          {{- if and .Values.argocdIngress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: {{ .Values.argocdIngress.pathType }}
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ include "kubernetes-2025.fullname" . }}
              port:
                number: {{ .Values.argocdIngress.servicePort }}
            {{- else }}
            serviceName: {{ .Values.argocdIngress.serviceName }}
            servicePort: {{ .Values.argocdIngress.servicePort }}
            {{- end }}
{{- end }}